version: "3.4"

services:
  api:
    build: .
    container_name: PlaylistService
    networks:
      - my_network
    hostname: PlaylistServiceApplication
    depends_on:
      -   postgres
    environment:
      - POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: on-failure
  postgres:
    image: postgres:15-alpine
    container_name: postgresContainerForPlaylistService
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: PlaylistService
      PGDATA: /data/postgres
    networks:
      - my_network
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadminContainerForPlaylistService
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ad@min.ru
      PGADMIN_DEFAULT_PASSWORD: pgpassword
    networks:
      - my_network
    ports:
      - 8081:80
volumes:
  postgres_storage:
    name: PlaylistServiceApplicationVolume

networks:
  my_network:
    driver: bridge

